# Version: 1.3.5 
Vagrant.configure("2") do |config|
  vm_name = ENV['VAGRANT_VM_NAME'] || 'default'

  config.vm.synced_folder '.', '/share', disabled: true
  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'

  config.vm.define "opnsense" do |opnsense|
    opnsense.vm.box = "axenedu/opnsense-20.1"
    opnsense.vm.hostname = "opnsense"
 
    opnsense.vm.network "private_network", type: "dhcp", virtualbox__intnet: true
    # opnsense.vm.network "private_network", ip: '192.168.10.60', virtualbox__intnet: true
 
    opnsense.vm.provider "virtualbox" do |vb|
      vb.name = "opnSense"
      vb.memory = "2048"
      vb.cpus = "2"
      vb.gui = true
    end
  end
  
  config.vm.define "pfsense" do |pfsense|
    pfsense.vm.box = "prof-ninjason/pfSense"
    pfsense.vm.hostname = "pfsense"
 
    pfsense.vm.network "private_network", type: "dhcp", virtualbox__intnet: true
    # pfsense.vm.network "private_network", ip: '192.168.10.60', virtualbox__intnet: true
 
    pfsense.vm.provider "virtualbox" do |vb|
      vb.name = "pfSense"
      vb.memory = "2048"
      vb.cpus = "2"
      vb.gui = true
    end
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "prof-ninjason/ubuntu"
    ubuntu.vm.hostname = "ubuntu"

    ubuntu.vm.network "private_network", type: "dhcp", virtualbox__intnet: true

    ubuntu.vm.provider "virtualbox" do |vb|
      vb.name = "Ubuntu"
      vb.memory = "4096"
      vb.cpus = "2"
      vb.gui = true
    end
  end
  
  config.vm.define "alpine" do |alpine|
    alpine.vm.box = "generic/alpine318"
    alpine.vm.hostname = "alpine"

    alpine.vm.network "private_network", type: "dhcp", virtualbox__intnet: true

    alpine.vm.provider "virtualbox" do |vb|
      vb.name = "Alpine"
      vb.memory = "4096"
      vb.cpus = "2"
      vb.gui = true
    end
  end

  config.vm.define "centos" do |centos|
    centos.vm.box = "generic/centos7"
    centos.vm.hostname = "centos"

    centos.vm.network "private_network", type: "dhcp", virtualbox__intnet: true

    centos.vm.provider "virtualbox" do |vb|
      vb.name = "Centos"
      vb.memory = "4096"
      vb.cpus = "2"
      vb.gui = true
    end
  end
  
  config.vm.define "splunk" do |splunk|
    splunk.vm.box = "prof-ninjason/splunk"
    splunk.vm.hostname = "splunk"

    splunk.vm.network "private_network", type: "dhcp", virtualbox__intnet: true

    splunk.vm.provider "virtualbox" do |vb|
      vb.name = "Splunk"
      vb.memory = "4096"
      vb.cpus = "2"
      vb.gui = true
    end
  end
  
  config.vm.define "ub1404" do |ub1404|
    ub1404.vm.box = "rapid7/metasploitable3-ub1404"
    ub1404.vm.hostname = "ub1404"

    ub1404.vm.network "private_network", type: "dhcp", virtualbox__intnet: true

    ub1404.vm.provider "virtualbox" do |vb|
      vb.name = "ub1404"
      vb.memory = "2048"
      vb.cpus = "2"
      vb.gui = true
    end
  end
  
  config.vm.define "greenbone" do |greenbone|
    greenbone.vm.box = "prof-ninjason/greenbone"
    greenbone.vm.hostname = "greenbone"

    greenbone.vm.network "private_network", type: "dhcp", virtualbox__intnet: true

    greenbone.vm.provider "virtualbox" do |vb|
      vb.name = "Greenbone"
      vb.memory = "4096"
      vb.cpus = "2"
      vb.gui = true
    end
  end

  config.vm.define "owasp" do |owasp|
    owasp.vm.box = "prof-ninjason/owasp"
    owasp.vm.hostname = "owasp"

    owasp.vm.network "private_network", type: "dhcp", virtualbox__intnet: true

    owasp.vm.provider "virtualbox" do |vb|
      vb.name = "owasp"
      vb.memory = "2048"
      vb.cpus = "2"
      vb.gui = true
    end
  end

  config.vm.define "kali" do |kali|
    kali.vm.box = "prof-ninjason/kali"
    kali.vm.box = "kalilinux/rolling"
	kali.vm.hostname = "kali"
 
    kali.vm.network "private_network", type: "dhcp", virtualbox__intnet: true

    kali.vm.provider "virtualbox" do |vb|
      vb.name = "Kali"
      vb.memory = "2048"
      vb.cpus = "2"
      vb.gui = true
    end
  end

  config.vm.define "parrot" do |parrot|
    parrot.vm.box = "prof-ninjason/kali"
    parrot.vm.hostname = "parrot"

    parrot.vm.network "private_network", type: "dhcp", virtualbox__intnet: true

    parrot.vm.provider "virtualbox" do |vb|
      vb.name = "Parrot"
      vb.memory = "4096"
      vb.cpus = "2"
      vb.gui = true
    end
  end

  config.vm.define "alpine" do |alpine|
    alpine.vm.box = "generic/alpine319"
    alpine.vm.hostname = "alpine"

    alpine.vm.network "private_network", type: "dhcp", virtualbox__intnet: true

    alpine.vm.provider "virtualbox" do |vb|
      vb.name = "Alpine"
      vb.memory = "4096"
      vb.cpus = "2"
      vb.gui = true
    end
  end

  config.vm.define "onion" do |onion|
    # onion.vm.box = "prof-ninjason/onion"
    onion.vm.box = "dlee35/securityonion"
    onion.vm.hostname = "onion"
 
    onion.vm.network "private_network", type: "dhcp", virtualbox__intnet: true
    onion.vm.network "private_network", type: "dhcp", virtualbox__intnet: true

    onion.vm.provider "virtualbox" do |vb|
      vb.name = "Onion"
      vb.memory = "12288"
      vb.cpus = "4"
      vb.gui = true
    end
  end

  config.vm.define "android" do |android|
    # android.vm.box = "prof-ninjason/android"
    android.vm.box = "motiv/android"
    android.vm.hostname = "android"
 
    android.vm.network "private_network", type: "dhcp", virtualbox__intnet: true
    android.vm.network "private_network", type: "dhcp", virtualbox__intnet: true

    android.vm.provider "virtualbox" do |vb|
      vb.name = "Android"
      vb.memory = "12288"
      vb.cpus = "4"
      vb.gui = true
    end
  end

  if vm_name.start_with?('w')
    config.vm.provision 'shell', inline: <<-EOF
      cmd /c ver
      Get-ComputerInfo
    EOF
  else
    config.vm.provision 'shell', inline: <<-EOF
      uname -a
      lsb_release -a
      lshw
      apt list --installed
    EOF
  end
end
