Vagrant.configure("2") do |config|
  config.vm.define "kalipurple" do |kalipurple|
    kalipurple.vm.box = "prof-ninjason/kalipurple"
    kalipurple.vm.hostname = "kalipurple"

    kalipurple.ssh.private_key_path = "~/.ssh/id_rsa"
    kalipurple.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/authorized_keys"

    kalipurple.vm.network "private_network", type: "dhcp", virtualbox__intnet: true

    kalipurple.vm.provider "virtualbox" do |vb|
      vb.name = "Kali Purple"
      vb.memory = "8192"
      vb.cpus = "4"
      vb.gui = true
    end
  end  
end
